### ISSUE TITLE
How to understand position embedding?

### ISSUE THREAD

**Issue by machanic** [soskek/attention_is_all_you_need#5]
Can you explain codes in https://github.com/soskek/attention_is_all_you_need/blob/master/net.py#L308-L340, I have to implemented the code of another similar paper which is inspired by "all you need": https://arxiv.org/pdf/1711.11575.pdf , in bottom of page 3. The author said: This 4-d feature is embedded to a high-dimensional representation by method in [49], which computes cosine and sine functions of different wavelengths. The feature dimension after embedding is dg.

How to understand the position sin& cos embedding, I have read the two paper, And I still can not understand this part.

**Comment by machanic** [comment]
Can you help me, please!

**Comment by soskek** [comment]
If you want to ask about an algorithm or content itself in the papers, it would be better to ask the authors.

**Comment by machanic** [comment]
@soskek Why the code of position embedding of https://github.com/soskek/attention_is_all_you_need/blob/master/net.py#L308-L340 and https://github.com/soskek/attention_is_all_you_need/blob/master/Observe_Position_Encoding.ipynb is different? Does they do the same thing??
Can you give me some insights about how to understand it? Or does it just replicate of paper formular?

**Comment by machanic** [comment]
@soskek I test the two function results. which is different of calcuate result?

**Comment by soskek** [comment]
As my comment out in the code already said (`Implementation in the Google tensor2tensor repo`), it is used in tensor2tensor official implementation.
https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/layers/common_attention.py#L359-L403
For question about that, it would be better to ask the authors or contributors of the repository.
